remote_theme: 1000101/texture
#theme: jekyll-theme-cayman
title: NixOS Online
author: 1000101
email: b1000101@pm.me
description: > # this means to ignore newlines until "show_exerpts:"
  NixOS vs 1000101
show_excerpts: true # set to true to show excerpts on the homepage

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: [1000101][link-mainpage]
  tagline: Bleep. Blop.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  analytics_id: "UA-20404460-11"
  disqus_shortname: nixos-online

  # generate social links in footer
  social_links:
    github:  1000101
 
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

[link-mainpage]: https://nixos.online/